### ISSUE TITLE
typescript教程修改建议

### ISSUE THREAD

**Issue by FreyaOne** [datawhalechina/wow-fullstack#26]
1. 在开源教程typescript第5章中第二节中，使用了fastApi在模拟后端，但是并没有说这个环境是如何搭建的，这其实在别的模块有介绍，更好的方式是在那里添加一句引言，如果不知道如何搭建这个后端测试环境，可以参考xxx教程
2. 在typescript的高级部分，个人阅读起来就感觉写的比较仓促，不论是内容还是格式，可以再修改调整下。

**Comment by omige** [comment]
已经修改，请再次查看ts 5.2 节。

**Comment by omige** [comment]
谢谢宝贵意见！
